Vagrant.configure("2") do |config|

  config.vm.define "kubeWorker1" do |kubeWorker1|
    kubeWorker1.vm.box = "peru/ubuntu-18.04-server-amd64"
    kubeWorker1.vm.network "public_network", ip: "192.168.1.6"
    kubeWorker1.vm.provision "shell", path: "script-workers.sh"
    kubeWorker1.vm.provider "virtualbox" do |vb|
      vb.name = "kube-worker1"
      vb.gui = false
      vb.memory = "2048"
      vb.cpus = 2
    end
  end

  config.vm.define "kubeMaster" do |kubeMaster|
    kubeMaster.vm.box = "peru/ubuntu-18.04-server-amd64"
    kubeMaster.vm.network "public_network", ip: "192.168.1.5"
    kubeMaster.vm.provision "shell", path: "script-master.sh"
    kubeMaster.vm.provider "virtualbox" do |vb|
      vb.name = "kube-master"
      vb.gui = false
      vb.memory = "2048"
      vb.cpus = 2
    end
  end  
end