apiVersion: apps/v1
kind: Deployment
metadata:
  name: alopezfu-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alopezfu
  template:
    metadata:
      labels:
        app: alopezfu
    spec:
      containers:
        - name: lamp
          image: mattrayner/lamp
          volumeMounts:
            - name: alopezfu-pvc
              mountPath: /app
      volumes:
        - name: alopezfu-pvc
          hostPath:
            path: /data/alopezfu
            type: Directory
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: alopezfu-ingress
spec:
  rules:
  - host: alopezfu.rock.com
    http:
      paths:
      - path: /
        backend:
          serviceName: alopezfu-service
          servicePort: port-apache
---
apiVersion: v1
kind: Service
metadata:
  name: alopezfu-service
spec:
  selector:
    app: alopezfu
  ports:
  - name: port-apache
    port: 80
    targetPort: 80